//
//  PostalCodeSearchViewController.swift
//  signupfirebase
//
//  Created by Jan  on 21/01/2019.
//  Copyright © 2019 Jan . All rights reserved.
//

import UIKit

var city = ""
var oldCity = ""
var postalCode = ""
var oldPostalCode = ""

class PostalCodeSearchViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate {
    var postalCodes: [PostalCode] = [
        PostalCode(code: "0001", city: "Oslo"),
        PostalCode(code: "1300", city: "Sandvika"),
        PostalCode(code: "1305", city: "Haslum"),
        PostalCode(code: "1306", city: "Sandvika"),
        PostalCode(code: "1307", city: "Fornebu"),
        PostalCode(code: "1308", city: "Jar"),
        PostalCode(code: "1309", city: "Rud"),
        PostalCode(code: "1311", city: "Høvikodden"),
        PostalCode(code: "1312", city: "Slependen"),
        PostalCode(code: "1313", city: "Vøyenenga"),
        PostalCode(code: "1316", city: "Eiksmarka"),
        PostalCode(code: "1317", city: "Bærums Verk"),
        PostalCode(code: "1319", city: "Bekkestua"),
        PostalCode(code: "1321", city: "Stabekk"),
        PostalCode(code: "1322", city: "Høvik"),
        PostalCode(code: "1323", city: "Høvik"),
        PostalCode(code: "1324", city: "Lysaker"),
        PostalCode(code: "1328", city: "Høvik"),
        PostalCode(code: "1329", city: "Lommedalen"),
        PostalCode(code: "1330", city: "Fornebu"),
        PostalCode(code: "4001", city: "Stavanger"),
        PostalCode(code: "4002", city: "Stavanger"),
        PostalCode(code: "4003", city: "Stavanger"),
        PostalCode(code: "4004", city: "Stavanger"),
        PostalCode(code: "4005", city: "Stavanger"),
        PostalCode(code: "4006", city: "Stavanger"),
        PostalCode(code: "4007", city: "Stavanger"),
        PostalCode(code: "4008", city: "Stavanger"),
        PostalCode(code: "4009", city: "Stavanger"),
        PostalCode(code: "4010", city: "Stavanger"),
        PostalCode(code: "4011", city: "Stavanger"),
        PostalCode(code: "4012", city: "Stavanger"),
        PostalCode(code: "4013", city: "Stavanger"),
        PostalCode(code: "4014", city: "Stavanger"),
        PostalCode(code: "4015", city: "Stavanger"),
        PostalCode(code: "4016", city: "Stavanger"),
        PostalCode(code: "4017", city: "Stavanger"),
        PostalCode(code: "4018", city: "Stavanger"),
        PostalCode(code: "4019", city: "Stavanger"),
        PostalCode(code: "4020", city: "Stavanger"),
        PostalCode(code: "4021", city: "Stavanger"),
        PostalCode(code: "4022", city: "Stavanger"),
        PostalCode(code: "4023", city: "Stavanger"),
        PostalCode(code: "4024", city: "Stavanger"),
        PostalCode(code: "4025", city: "Stavanger"),
        PostalCode(code: "4026", city: "Stavanger"),
        PostalCode(code: "4027", city: "Stavanger"),
        PostalCode(code: "4028", city: "Stavanger"),
        PostalCode(code: "4029", city: "Stavanger"),
        PostalCode(code: "4031", city: "Stavanger"),
        PostalCode(code: "4032", city: "Stavanger"),
        PostalCode(code: "4033", city: "Stavanger"),
        PostalCode(code: "4034", city: "Stavanger"),
        PostalCode(code: "4035", city: "Stavanger"),
        PostalCode(code: "4036", city: "Stavanger"),
        PostalCode(code: "4041", city: "Hafrsfjord"),
        PostalCode(code: "4042", city: "Hafrsfjord"),
        PostalCode(code: "4043", city: "Hafrsfjord"),
        PostalCode(code: "4044", city: "Hafrsfjord"),
        PostalCode(code: "4045", city: "Hafrsfjord"),
        PostalCode(code: "4046", city: "Hafrsfjord"),
        PostalCode(code: "4047", city: "Hafrsfjord"),
        PostalCode(code: "4048", city: "Hafrsfjord"),
        PostalCode(code: "4049", city: "Hafrsfjord"),
        PostalCode(code: "4050", city: "Sola"),
        PostalCode(code: "4051", city: "Sola"),
        PostalCode(code: "4052", city: "Røyneberg"),
        PostalCode(code: "4053", city: "Ræge"),
        PostalCode(code: "4054", city: "Tjelta"),
        PostalCode(code: "4055", city: "Sola"),
        PostalCode(code: "4056", city: "Tananger"),
        PostalCode(code: "4057", city: "Tananger"),
        PostalCode(code: "4058", city: "Tananger"),
        PostalCode(code: "4059", city: "Røyneberg"),
        PostalCode(code: "4063", city: "Tjelta"),
        PostalCode(code: "4064", city: "Stavanger"),
        PostalCode(code: "4065", city: "Stavanger"),
        PostalCode(code: "4066", city: "Stavanger"),
        PostalCode(code: "4067", city: "Stavanger"),
        PostalCode(code: "4068", city: "Stavanger"),
        PostalCode(code: "4069", city: "Stavanger"),
        PostalCode(code: "4070", city: "Randaberg"),
        PostalCode(code: "4071", city: "Randaberg"),
        PostalCode(code: "4072", city: "Randaberg"),
        PostalCode(code: "4073", city: "Randaberg"),
        PostalCode(code: "4076", city: "Vassøy"),
        PostalCode(code: "4077", city: "Hundvåg"),
        PostalCode(code: "4078", city: "Stavanger"),
        PostalCode(code: "4079", city: "Stavanger"),
        PostalCode(code: "4081", city: "Stavanger"),
        PostalCode(code: "4082", city: "Stavanger"),
        PostalCode(code: "4083", city: "Hundvåg"),
        PostalCode(code: "4084", city: "Stavanger"),
        PostalCode(code: "4085", city: "Hundvåg"),
        PostalCode(code: "4086", city: "Hundvåg"),
        PostalCode(code: "4087", city: "Stavanger"),
        PostalCode(code: "4088", city: "Stavanger"),
        PostalCode(code: "4089", city: "Hafrsfjord"),
        PostalCode(code: "4090", city: "Hafrsfjord"),
        PostalCode(code: "4091", city: "Hafrsfjord"),
        PostalCode(code: "4092", city: "Stavanger"),
        PostalCode(code: "4093", city: "Stavanger"),
        PostalCode(code: "4094", city: "Stavanger"),
        PostalCode(code: "4095", city: "Stavanger"),
        PostalCode(code: "4096", city: "Randaberg"),
        PostalCode(code: "4097", city: "Sola"),
        PostalCode(code: "4098", city: "Tananger "),
        PostalCode(code: "4099", city: "Stavanger"),
        PostalCode(code: "4100", city: "Jørpeland"),
        PostalCode(code: "4102", city: "Idse"),
        PostalCode(code: "4110", city: "Forsand"),
        PostalCode(code: "4119", city: "Forsand"),
        PostalCode(code: "4120", city: "Tau"),
        PostalCode(code: "4123", city: "Sør-Hidle"),
        PostalCode(code: "4124", city: "Tau"),
        PostalCode(code: "4126", city: "Jørpeland"),
        PostalCode(code: "4127", city: "Lysebotn"),
        PostalCode(code: "4128", city: "Fløyrli"),
        PostalCode(code: "4129", city: "Songesand"),
        PostalCode(code: "4130", city: "Hjelmeland"),
        PostalCode(code: "4134", city: "Jøsenfjorden"),
        PostalCode(code: "4137", city: "Årdal i Ryfylke"),
        PostalCode(code: "4139", city: "Fister"),
        PostalCode(code: "4146", city: "Skiftun"),
        PostalCode(code: "4148", city: "Hjelmeland"),
        PostalCode(code: "4150", city: "Rennesøy"),
        PostalCode(code: "4152", city: "Vestre Åmøy"),
        PostalCode(code: "4153", city: "Brimse"),
        PostalCode(code: "4154", city: "Austre Åmøy"),
        PostalCode(code: "4156", city: "Mosterøy"),
        PostalCode(code: "4158", city: "Bru"),
        PostalCode(code: "4159", city: "Rennesøy"),
        PostalCode(code: "4160", city: "Finnøy"),
        PostalCode(code: "4161", city: "Finnøy"),
        PostalCode(code: "4163", city: "Talgje"),
        PostalCode(code: "4164", city: "Fogn"),
        PostalCode(code: "4167", city: "Helgøy i Ryfylke"),
        PostalCode(code: "4168", city: "Byre"),
        PostalCode(code: "4169", city: "Sørbokn"),
        PostalCode(code: "4170", city: "Sjernarøy"),
        PostalCode(code: "4173", city: "Nord-Hidle"),
        PostalCode(code: "4174", city: "Sjernarøy"),
        PostalCode(code: "4180", city: "Kvitsøy"),
        PostalCode(code: "4181", city: "Kvitsøy"),
        PostalCode(code: "4182", city: "Skartveit"),
        PostalCode(code: "4187", city: "Ombo"),
        PostalCode(code: "4198", city: "Foldøy"),
        PostalCode(code: "4200", city: "Sauda"),
        PostalCode(code: "4201", city: "Sauda"),
        PostalCode(code: "4208", city: "Saudasjøen"),
        PostalCode(code: "4209", city: "Vanvik"),
        PostalCode(code: "4230", city: "Sand"),
        PostalCode(code: "4233", city: "Erfjord"),
        PostalCode(code: "4234", city: "Jelsa"),
        PostalCode(code: "4235", city: "Hebnes"),
        PostalCode(code: "4237", city: "Suldalsosen"),
        PostalCode(code: "4239", city: "Sand"),
        PostalCode(code: "4240", city: "Suldalsosen"),
        PostalCode(code: "4244", city: "Nesflaten"),
        PostalCode(code: "4250", city: "Kopervik"),
        PostalCode(code: "4260", city: "Torvastad"),
        PostalCode(code: "4262", city: "Avaldsnes"),
        PostalCode(code: "4264", city: "Kvalavåg"),
        PostalCode(code: "4265", city: "Håvik"),
        PostalCode(code: "4270", city: "Åkrehamn"),
        PostalCode(code: "4272", city: "Sandve"),
        PostalCode(code: "4274", city: "Stol"),
        PostalCode(code: "4275", city: "Sævelandsvik"),
        PostalCode(code: "4276", city: "Veavågen"),
        PostalCode(code: "4280", city: "Skudeneshavn"),
        PostalCode(code: "4291", city: "Kopervik"),
        PostalCode(code: "4294", city: "Kopervik"),
        PostalCode(code: "4295", city: "Veavågen"),
        PostalCode(code: "4296", city: "Åkrehamn"),
        PostalCode(code: "4297", city: "Skudeneshavn"),
        PostalCode(code: "4298", city: "Torvastad"),
        PostalCode(code: "4299", city: "Avaldsnes"),
        PostalCode(code: "4301", city: "Sandnes"),
        PostalCode(code: "4302", city: "Sandnes"),
        PostalCode(code: "4306", city: "Sandnes"),
        PostalCode(code: "4307", city: "Sandnes"),
        PostalCode(code: "4308", city: "Sandnes"),
        PostalCode(code: "4309", city: "Sandnes"),
        PostalCode(code: "4310", city: "Hommersåk"),
        PostalCode(code: "4311", city: "Hommersåk"),
        PostalCode(code: "4312", city: "Sandnes"),
        PostalCode(code: "4313", city: "Sandnes"),
        PostalCode(code: "4314", city: "Sandnes"),
        PostalCode(code: "4315", city: "Sandnes"),
        PostalCode(code: "4316", city: "Sandnes"),
        PostalCode(code: "4317", city: "Sandnes"),
        PostalCode(code: "4318", city: "Sandnes"),
        PostalCode(code: "4319", city: "Sandnes"),
        PostalCode(code: "4320", city: "Sandnes"),
        PostalCode(code: "4321", city: "Sandnes"),
        PostalCode(code: "4322", city: "Sandnes"),
        PostalCode(code: "4323", city: "Sandnes"),
        PostalCode(code: "4324", city: "Sandnes"),
        PostalCode(code: "4325", city: "Sandnes"),
        PostalCode(code: "4326", city: "Sandnes"),
        PostalCode(code: "4327", city: "Sandnes"),
        PostalCode(code: "4328", city: "Sandnes"),
        PostalCode(code: "4329", city: "Sandnes"),
        PostalCode(code: "4330", city: "Ålgård"),
        PostalCode(code: "4332", city: "Figgjo"),
        PostalCode(code: "4333", city: "Oltedal"),
        PostalCode(code: "4335", city: "Dirdal"),
        PostalCode(code: "4336", city: "Sandnes"),
        PostalCode(code: "4337", city: "Sandnes"),
        PostalCode(code: "4338", city: "Sandnes"),
        PostalCode(code: "4339", city: "Ålgård"),
        PostalCode(code: "4340", city: "Bryne"),
        PostalCode(code: "4341", city: "Bryne"),
        PostalCode(code: "4342", city: "Undheim"),
        PostalCode(code: "4343", city: "Orre"),
        PostalCode(code: "4344", city: "Bryne"),
        PostalCode(code: "4345", city: "Bryne"),
        PostalCode(code: "4346", city: "Bryne"),
        PostalCode(code: "4347", city: "Lye"),
        PostalCode(code: "4348", city: "Lye"),
        PostalCode(code: "4349", city: "Bryne"),
        PostalCode(code: "4352", city: "Kleppe"),
        PostalCode(code: "4353", city: "Klepp Stasjon"),
        PostalCode(code: "4354", city: "Voll"),
        PostalCode(code: "4355", city: "Kvernaland"),
        PostalCode(code: "4356", city: "Kvernaland"),
        PostalCode(code: "4357", city: "Klepp Stasjon"),
        PostalCode(code: "4358", city: "Kleppe"),
        PostalCode(code: "4360", city: "Varhaug"),
        PostalCode(code: "4361", city: "Sirevåg"),
        PostalCode(code: "4362", city: "Vigrestad"),
        PostalCode(code: "4363", city: "Brusand"),
        PostalCode(code: "4364", city: "Sirevåg"),
        PostalCode(code: "4365", city: "Nærbø"),
        PostalCode(code: "4367", city: "Nærbø"),
        PostalCode(code: "4368", city: "Varhaug"),
        PostalCode(code: "4369", city: "Vigrestad"),
        PostalCode(code: "4370", city: "Egersund"),
        PostalCode(code: "4371", city: "Egersund"),
        PostalCode(code: "4372", city: "Egersund"),
        PostalCode(code: "4373", city: "Egersund"),
        PostalCode(code: "4374", city: "Egersund"),
        PostalCode(code: "4375", city: "Hellvik"),
        PostalCode(code: "4376", city: "Helleland"),
        PostalCode(code: "4378", city: "Egersund"),
        PostalCode(code: "4379", city: "Egersund"),
        PostalCode(code: "4380", city: "Hauge i Dalane"),
        PostalCode(code: "4381", city: "Hauge i Dalane"),
        PostalCode(code: "4384", city: "Vikeså"),
        PostalCode(code: "4385", city: "Helleland"),
        PostalCode(code: "4387", city: "Bjerkreim"),
        PostalCode(code: "4389", city: "Vikeså"),
        PostalCode(code: "4390", city: "Oltedal"),
        PostalCode(code: "4391", city: "Sandnes"),
        PostalCode(code: "4392", city: "Sandnes"),
        PostalCode(code: "4393", city: "Sandnes"),
        PostalCode(code: "4394", city: "Sandnes"),
        PostalCode(code: "4395", city: "Hommersåk"),
        PostalCode(code: "4396", city: "Sandnes"),
        PostalCode(code: "4397", city: "Sandnes"),
        PostalCode(code: "4398", city: "Sandnes"),
        PostalCode(code: "4399", city: "Sandnes"),
        PostalCode(code: "4400", city: "Flekkefjord"),
        PostalCode(code: "4401", city: "Flekkefjord"),
        PostalCode(code: "4402", city: "Flekkefjord"),
        PostalCode(code: "4403", city: "Flekkefjord"),
        PostalCode(code: "4420", city: "Åna-Sira"),
        PostalCode(code: "4432", city: "Hidrasund"),
        PostalCode(code: "4434", city: "Andabeløy"),
        PostalCode(code: "4436", city: "Gyland"),
        PostalCode(code: "4438", city: "Sira"),
        PostalCode(code: "4439", city: "Sira"),
        PostalCode(code: "4440", city: "Tonstad"),
        PostalCode(code: "4441", city: "Tonstad"),
        PostalCode(code: "4443", city: "Tjørhom"),
        PostalCode(code: "4460", city: "Moi"),
        PostalCode(code: "4462", city: "Hovsherad"),
        PostalCode(code: "4463", city: "Ualand"),
        PostalCode(code: "4465", city: "Moi"),
        PostalCode(code: "4473", city: "Kvinlog"),
        PostalCode(code: "4480", city: "Kvinesdal"),
        PostalCode(code: "4484", city: "Øyestranda"),
        PostalCode(code: "4485", city: "Feda"),
        PostalCode(code: "4490", city: "Kvinesdal"),
        PostalCode(code: "4491", city: "Kvinesdal"),
        PostalCode(code: "4492", city: "Kvinesdal"),
        PostalCode(code: "4501", city: "Mandal"),
        PostalCode(code: "4502", city: "Mandal"),
        PostalCode(code: "4503", city: "Mandal"),
        PostalCode(code: "4504", city: "Mandal"),
        PostalCode(code: "4507", city: "Mandal"),
        PostalCode(code: "4508", city: "Mandal"),
        PostalCode(code: "4509", city: "Mandal"),
        PostalCode(code: "4513", city: "Mandal"),
        PostalCode(code: "4514", city: "Mandal"),
        PostalCode(code: "4515", city: "Mandal"),
        PostalCode(code: "4516", city: "Mandal"),
        PostalCode(code: "4517", city: "Mandal"),
        PostalCode(code: "4519", city: "Holum"),
        PostalCode(code: "4520", city: "Lindesnes"),
        PostalCode(code: "4521", city: "Lindesnes"),
        PostalCode(code: "4522", city: "Lindesnes"),
        PostalCode(code: "4523", city: "Lindesnes"),
        PostalCode(code: "4524", city: "Lindesnes"),
        PostalCode(code: "4525", city: "Konsmo"),
        PostalCode(code: "4526", city: "Konsmo"),
        PostalCode(code: "4528", city: "Kollungtveit"),
        PostalCode(code: "4529", city: "Byremo"),
        PostalCode(code: "4532", city: "Øyslebø"),
        PostalCode(code: "4534", city: "Marnardal"),
        PostalCode(code: "4535", city: "Marnardal"),
        PostalCode(code: "4536", city: "Bjelland"),
        PostalCode(code: "4540", city: "Åseral"),
        PostalCode(code: "4541", city: "Åseral"),
        PostalCode(code: "4544", city: "Fossdal"),
        PostalCode(code: "4550", city: "Farsund"),
        PostalCode(code: "4551", city: "Farsund"),
        PostalCode(code: "4552", city: "Farsund"),
        PostalCode(code: "4553", city: "Farsund"),
        PostalCode(code: "4554", city: "Farsund"),
        PostalCode(code: "4557", city: "Vanse"),
        PostalCode(code: "4558", city: "Vanse"),
        PostalCode(code: "4560", city: "Vanse"),
        PostalCode(code: "4563", city: "Borhaug"),
        PostalCode(code: "4575", city: "Lyngdal"),
        PostalCode(code: "4576", city: "Lyngdal"),
        PostalCode(code: "4577", city: "Lyngdal"),
        PostalCode(code: "4579", city: "Lyngdal"),
        PostalCode(code: "4580", city: "Lyngdal"),
        PostalCode(code: "4586", city: "Korshamn"),
        PostalCode(code: "4588", city: "Kvås"),
        PostalCode(code: "4590", city: "Snartemo"),
        PostalCode(code: "4595", city: "Tingvatn"),
        PostalCode(code: "4596", city: "Eiken"),
        PostalCode(code: "4597", city: "Eiken"),
        PostalCode(code: "4604", city: "Kristiansand S"),
        PostalCode(code: "4605", city: "Kristiansand S"),
        PostalCode(code: "4606", city: "Kristiansand S"),
        PostalCode(code: "4608", city: "Kristiansand S"),
        PostalCode(code: "4609", city: "Kardemomme By"),
        PostalCode(code: "4610", city: "Kristiansand S"),
        PostalCode(code: "4611", city: "Kristiansand S"),
        PostalCode(code: "4612", city: "Kristiansand S"),
        PostalCode(code: "4613", city: "Kristiansand S"),
        PostalCode(code: "4614", city: "Kristiansand S"),
        PostalCode(code: "4615", city: "Kristiansand S"),
        PostalCode(code: "4616", city: "Kristiansand S"),
        PostalCode(code: "4617", city: "Kristiansand S"),
        PostalCode(code: "4618", city: "Kristiansand S"),
        PostalCode(code: "4619", city: "Mosby"),
        PostalCode(code: "4620", city: "Kristiansand S"),
        PostalCode(code: "4621", city: "Kristiansand S"),
        PostalCode(code: "4622", city: "Kristiansand S"),
        PostalCode(code: "4623", city: "Kristiansand S"),
        PostalCode(code: "4624", city: "Kristiansand S"),
        PostalCode(code: "4625", city: "Flekkerøy"),
        PostalCode(code: "4626", city: "Kristiansand S"),
        PostalCode(code: "4628", city: "Kristiansand S"),
        PostalCode(code: "4629", city: "Kristiansand S"),
        PostalCode(code: "4630", city: "Kristiansand S"),
        PostalCode(code: "4631", city: "Kristiansand S"),
        PostalCode(code: "4632", city: "Kristiansand S"),
        PostalCode(code: "4633", city: "Kristiansand S"),
        PostalCode(code: "4634", city: "Kristiansand S"),
        PostalCode(code: "4635", city: "Kristiansand S"),
        PostalCode(code: "4636", city: "Kristiansand S"),
        PostalCode(code: "4637", city: "Kristiansand S"),
        PostalCode(code: "4638", city: "Kristiansand S"),
        PostalCode(code: "4639", city: "Kristiansand S"),
        PostalCode(code: "4640", city: "Søgne"),
        PostalCode(code: "4641", city: "Søgne"),
        PostalCode(code: "4642", city: "Søgne"),
        PostalCode(code: "4643", city: "Søgne"),
        PostalCode(code: "4644", city: "Søgne"),
        PostalCode(code: "4645", city: "Nodeland"),
        PostalCode(code: "4646", city: "Finsland"),
        PostalCode(code: "4647", city: "Brennåse"),
        PostalCode(code: "4649", city: "Finsland"),
        PostalCode(code: "4656", city: "Hamresanden"),
        PostalCode(code: "4657", city: "Kjevik"),
        PostalCode(code: "4658", city: "Tveit"),
        PostalCode(code: "4661", city: "Kristiansand S"),
        PostalCode(code: "4662", city: "Kristiansand S"),
        PostalCode(code: "4663", city: "Kristiansand S"),
        PostalCode(code: "4664", city: "Kristiansand S"),
        PostalCode(code: "4665", city: "Kristiansand S"),
        PostalCode(code: "4666", city: "Kristiansand S"),
        PostalCode(code: "4670", city: "Kristiansand S"),
        PostalCode(code: "4671", city: "Kristiansand S"),
        PostalCode(code: "4672", city: "Kristiansand S"),
        PostalCode(code: "4673", city: "Kristiansand S"),
        PostalCode(code: "4674", city: "Kristiansand S"),
        PostalCode(code: "4675", city: "Kristiansand S"),
        PostalCode(code: "4676", city: "Kristiansand S"),
        PostalCode(code: "4677", city: "Kristiansand S"),
        PostalCode(code: "4678", city: "Kristiansand S"),
        PostalCode(code: "4679", city: "Flekkerøy"),
        PostalCode(code: "4681", city: "Søgne"),
        PostalCode(code: "4682", city: "Søgne"),
        PostalCode(code: "4683", city: "Søgne"),
        PostalCode(code: "4684", city: "Brennåsen"),
        PostalCode(code: "4685", city: "Nodeland"),
        PostalCode(code: "4686", city: "Kristiansand S"),
        PostalCode(code: "4687", city: "Kristiansand S"),
        PostalCode(code: "4688", city: "Kristiansand S"),
        PostalCode(code: "4689", city: "Kristiansand S"),
        PostalCode(code: "4691", city: "Kristiansand S"),
        PostalCode(code: "4693", city: "Kristiansand S"),
        PostalCode(code: "4694", city: "Kristiansand S"),
        PostalCode(code: "4695", city: "Kristiansand S"),
        PostalCode(code: "4696", city: "Kristiansand S"),
        PostalCode(code: "4697", city: "Kristiansand S"),
        PostalCode(code: "4698", city: "Kristiansand S"),
        PostalCode(code: "4699", city: "Tveit"),
        PostalCode(code: "4700", city: "Vennesla"),
        PostalCode(code: "4701", city: "Vennesla"),
        PostalCode(code: "4702", city: "Vennesla"),
        PostalCode(code: "4703", city: "Vennesla"),
        PostalCode(code: "4705", city: "Øvrebø"),
        PostalCode(code: "4706", city: "Vennesla"),
        PostalCode(code: "4707", city: "Vennesla"),
        PostalCode(code: "4708", city: "Vennesla"),
        PostalCode(code: "4715", city: "Øvrebø"),
        PostalCode(code: "4720", city: "Hægeland"),
        PostalCode(code: "4721", city: "Hægeland"),
        PostalCode(code: "4724", city: "Iveland"),
        PostalCode(code: "4725", city: "Iveland"),
        PostalCode(code: "4730", city: "Vatnestrøm"),
        PostalCode(code: "4733", city: "Evje"),
        PostalCode(code: "4734", city: "Evje"),
        PostalCode(code: "4735", city: "Evje"),
        PostalCode(code: "4737", city: "Hornnes"),
        PostalCode(code: "4741", city: "Byglandsfjord"),
        PostalCode(code: "4742", city: "Grendi"),
        PostalCode(code: "4744", city: "Bygland"),
        PostalCode(code: "4745", city: "Bygland"),
        PostalCode(code: "4746", city: "Valle"),
        PostalCode(code: "4747", city: "Valle"),
        PostalCode(code: "4748", city: "Rysstad"),
        PostalCode(code: "4749", city: "Rysstad"),
        PostalCode(code: "4754", city: "Bykle"),
        PostalCode(code: "4755", city: "Hovden i Setesdal"),
        PostalCode(code: "4756", city: "Hovden i Setesdal"),
        PostalCode(code: "4760", city: "Birkeland"),
        PostalCode(code: "4766", city: "Herefoss"),
        PostalCode(code: "4768", city: "Engesland"),
        PostalCode(code: "4770", city: "Høvåg"),
        PostalCode(code: "4780", city: "Brekkestø"),
        PostalCode(code: "4790", city: "Lillesand"),
        PostalCode(code: "4791", city: "Lillesand"),
        PostalCode(code: "4792", city: "Lillesand"),
        PostalCode(code: "4793", city: "Høvåg"),
        PostalCode(code: "4794", city: "Lillesand"),
        PostalCode(code: "4795", city: "Birkeland"),
        PostalCode(code: "4801", city: "Arendal"),
        PostalCode(code: "4802", city: "Arendal"),
        PostalCode(code: "4803", city: "Arendal"),
        PostalCode(code: "4804", city: "Arendal"),
        PostalCode(code: "4808", city: "Arendal"),
        PostalCode(code: "4809", city: "Arendal"),
        PostalCode(code: "4810", city: "Eydehavn"),
        PostalCode(code: "4812", city: "Kongshavn"),
        PostalCode(code: "4815", city: "Saltrød"),
        PostalCode(code: "4816", city: "Kolbjørnsvik"),
        PostalCode(code: "4817", city: "His"),
        PostalCode(code: "4818", city: "Færvik"),
        PostalCode(code: "4820", city: "Froland"),
        PostalCode(code: "4821", city: "Rykene"),
        PostalCode(code: "4822", city: "Rykene"),
        PostalCode(code: "4823", city: "Nedenes"),
        PostalCode(code: "4824", city: "Bjorbekk"),
        PostalCode(code: "4825", city: "Arendal"),
        PostalCode(code: "4827", city: "Frolands Verk"),
        PostalCode(code: "4828", city: "Mjåvatn"),
        PostalCode(code: "4830", city: "Hynnekleiv"),
        PostalCode(code: "4832", city: "Mykland"),
        PostalCode(code: "4834", city: "Risdal"),
        PostalCode(code: "4836", city: "Arendal"),
        PostalCode(code: "4838", city: "Arendal"),
        PostalCode(code: "4839", city: "Arendal"),
        PostalCode(code: "4841", city: "Arendal"),
        PostalCode(code: "4842", city: "Arendal"),
        PostalCode(code: "4843", city: "Arendal"),
        PostalCode(code: "4844", city: "Arendal"),
        PostalCode(code: "4846", city: "Arendal"),
        PostalCode(code: "4847", city: "Arendal"),
        PostalCode(code: "4848", city: "Arendal"),
        PostalCode(code: "4849", city: "Arendal"),
        PostalCode(code: "4851", city: "Saltrød"),
        PostalCode(code: "4852", city: "Færvik"),
        PostalCode(code: "4853", city: "His"),
        PostalCode(code: "4854", city: "Nedenes"),
        PostalCode(code: "4855", city: "Froland"),
        PostalCode(code: "4856", city: "Arendal"),
        PostalCode(code: "4857", city: "Arendal"),
        PostalCode(code: "4858", city: "Arendal"),
        PostalCode(code: "4859", city: "Arendal"),
        PostalCode(code: "4862", city: "Eydehavn"),
        PostalCode(code: "4863", city: "Nelaug"),
        PostalCode(code: "4864", city: "Åmli"),
        PostalCode(code: "4865", city: "Åmli"),
        PostalCode(code: "4868", city: "Selåsvatn"),
        PostalCode(code: "4869", city: "Dølemo"),
        PostalCode(code: "4870", city: "Fevik"),
        PostalCode(code: "4876", city: "Grimstad"),
        PostalCode(code: "4877", city: "Grimstad"),
        PostalCode(code: "4878", city: "Grimstad"),
        PostalCode(code: "4879", city: "Grimstad"),
        PostalCode(code: "4884", city: "Grimstad"),
        PostalCode(code: "4885", city: "Grimstad"),
        PostalCode(code: "4886", city: "Grimstad"),
        PostalCode(code: "4887", city: "Grimstad"),
        PostalCode(code: "4888", city: "Homborsund"),
        PostalCode(code: "4889", city: "Fevik"),
        PostalCode(code: "4891", city: "Grimstad"),
        PostalCode(code: "4892", city: "Grimstad"),
        PostalCode(code: "4893", city: "Grimstad"),
        PostalCode(code: "4894", city: "Grimstad"),
        PostalCode(code: "4896", city: "Grimstad"),
        PostalCode(code: "4898", city: "Grimstad"),
        PostalCode(code: "4900", city: "Tvedestrand"),
        PostalCode(code: "4901", city: "Tvedestrand"),
        PostalCode(code: "4902", city: "Tvedestrand"),
        PostalCode(code: "4909", city: "Songe"),
        PostalCode(code: "4910", city: "Lyngør"),
        PostalCode(code: "4912", city: "Gjeving"),
        PostalCode(code: "4915", city: "Vestre Sandøya"),
        PostalCode(code: "4916", city: "Borøy"),
        PostalCode(code: "4920", city: "Staubø"),
        PostalCode(code: "4921", city: "Staubø"),
        PostalCode(code: "4934", city: "Nes Verk"),
        PostalCode(code: "4950", city: "Risør"),
        PostalCode(code: "4951", city: "Risør"),
        PostalCode(code: "4952", city: "Risør"),
        PostalCode(code: "4953", city: "Risør"),
        PostalCode(code: "4955", city: "Risør"),
        PostalCode(code: "4956", city: "Risør"),
        PostalCode(code: "4957", city: "Risør"),
        PostalCode(code: "4971", city: "Sundebru"),
        PostalCode(code: "4972", city: "Gjerstad"),
        PostalCode(code: "4973", city: "Vegårshei"),
        PostalCode(code: "4974", city: "Søndeled"),
        PostalCode(code: "4980", city: "Gjerstad"),
        PostalCode(code: "4985", city: "Vegårshei"),
        PostalCode(code: "4990", city: "Søndeled"),
        PostalCode(code: "4993", city: "Sundebru"),
        PostalCode(code: "4994", city: "Akland"),
        PostalCode(code: "5003", city: "Bergen"),
        PostalCode(code: "5004", city: "Bergen"),
        PostalCode(code: "5005", city: "Bergen"),
        PostalCode(code: "5006", city: "Bergen"),
        PostalCode(code: "5007", city: "Bergen"),
        PostalCode(code: "5008", city: "Bergen"),
        PostalCode(code: "5009", city: "Bergen"),
        PostalCode(code: "5010", city: "Bergen"),
        PostalCode(code: "5011", city: "Bergen"),
        PostalCode(code: "5012", city: "Bergen"),
        PostalCode(code: "5013", city: "Bergen"),
        PostalCode(code: "5014", city: "Bergen"),
        PostalCode(code: "5015", city: "Bergen"),
        PostalCode(code: "5016", city: "Bergen"),
        PostalCode(code: "5017", city: "Bergen"),
        PostalCode(code: "5018", city: "Bergen"),
        PostalCode(code: "5019", city: "Bergen"),
        PostalCode(code: "5020", city: "Bergen"),
        PostalCode(code: "5021", city: "Bergen"),
        PostalCode(code: "5022", city: "Bergen"),
        PostalCode(code: "5031", city: "Bergen"),
        PostalCode(code: "5032", city: "Bergen"),
        PostalCode(code: "5033", city: "Bergen"),
        PostalCode(code: "5034", city: "Bergen"),
        PostalCode(code: "5035", city: "Bergen"),
        PostalCode(code: "5036", city: "Bergen"),
        PostalCode(code: "5037", city: "Bergen"),
        PostalCode(code: "5038", city: "Bergen"),
        PostalCode(code: "5039", city: "Bergen"),
        PostalCode(code: "5041", city: "Bergen"),
        PostalCode(code: "5042", city: "Bergen"),
        PostalCode(code: "5043", city: "Bergen"),
        PostalCode(code: "5045", city: "Bergen"),
        PostalCode(code: "5052", city: "Bergen"),
        PostalCode(code: "5053", city: "Bergen"),
        PostalCode(code: "5054", city: "Bergen"),
        PostalCode(code: "5055", city: "Bergen"),
        PostalCode(code: "5056", city: "Bergen"),
        PostalCode(code: "5057", city: "Bergen"),
        PostalCode(code: "5058", city: "Bergen"),
        PostalCode(code: "5059", city: "Bergen"),
        PostalCode(code: "5063", city: "Bergen"),
        PostalCode(code: "5067", city: "Bergen"),
        PostalCode(code: "5068", city: "Bergen"),
        PostalCode(code: "5072", city: "Bergen"),
        PostalCode(code: "5073", city: "Bergen"),
        PostalCode(code: "5075", city: "Bergen"),
        PostalCode(code: "5081", city: "Bergen"),
        PostalCode(code: "5082", city: "Bergen"),
        PostalCode(code: "5089", city: "Bergen"),
        PostalCode(code: "5093", city: "Bergen"),
        PostalCode(code: "5094", city: "Bergen"),
        PostalCode(code: "5096", city: "Bergen"),
        PostalCode(code: "5097", city: "Bergen"),
        PostalCode(code: "5098", city: "Bergen"),
        PostalCode(code: "5099", city: "Bergen"),
        PostalCode(code: "5101", city: "Eidsvågneset"),
        PostalCode(code: "5104", city: "Eidsvåg i Åsane"),
        PostalCode(code: "5105", city: "Eidsvåg i Åsane"),
        PostalCode(code: "5106", city: "Øvre Ervik"),
        PostalCode(code: "5107", city: "Salhus"),
        PostalCode(code: "5108", city: "Hordvik"),
        PostalCode(code: "5109", city: "Hylkje"),
        PostalCode(code: "5111", city: "Breistein"),
        PostalCode(code: "5113", city: "Tertnes"),
        PostalCode(code: "5114", city: "Tertnes"),
        PostalCode(code: "5115", city: "Ulset"),
        PostalCode(code: "5116", city: "Ulset"),
        PostalCode(code: "5117", city: "Ulset"),
        PostalCode(code: "5118", city: "Ulset"),
        PostalCode(code: "5119", city: "Ulset"),
        PostalCode(code: "5121", city: "Ulset"),
        PostalCode(code: "5122", city: "Morvik"),
        PostalCode(code: "5124", city: "Morvik"),
        PostalCode(code: "5130", city: "Nyborg"),
        PostalCode(code: "5131", city: "Nyborg"),
        PostalCode(code: "5132", city: "Nyborg"),
        PostalCode(code: "5134", city: "Flaktveit"),
        PostalCode(code: "5135", city: "Flaktveit"),
        PostalCode(code: "5136", city: "Mjølkeråen"),
        PostalCode(code: "5137", city: "Mjølkeråen"),
        PostalCode(code: "5141", city: "Fyllingsdalen"),
        PostalCode(code: "5142", city: "Fyllingsdalen"),
        PostalCode(code: "5143", city: "Fyllingsdalen"),
        PostalCode(code: "5144", city: "Fyllingsdalen"),
        PostalCode(code: "5145", city: "Fyllingsdalen"),
        PostalCode(code: "5146", city: "Fyllingsdalen"),
        PostalCode(code: "5147", city: "Fyllingsdalen"),
        PostalCode(code: "5148", city: "Fyllingsdalen"),
        PostalCode(code: "5151", city: "Straumsgrend"),
        PostalCode(code: "5152", city: "Bønes"),
        PostalCode(code: "5153", city: "Bønes"),
        PostalCode(code: "5154", city: "Bønes"),
        PostalCode(code: "5155", city: "Bønes"),
        PostalCode(code: "5160", city: "Laksevåg"),
        PostalCode(code: "5161", city: "Laksevåg"),
        PostalCode(code: "5162", city: "Laksevåg"),
        PostalCode(code: "5163", city: "Laksevåg"),
        PostalCode(code: "5164", city: "Laksevåg"),
        PostalCode(code: "5165", city: "Laksevåg"),
        PostalCode(code: "5170", city: "Bjørndalstræ"),
        PostalCode(code: "5171", city: "Loddefjord"),
        PostalCode(code: "5172", city: "Loddefjord"),
        PostalCode(code: "5173", city: "Loddefjord"),
        PostalCode(code: "5174", city: "Mathopen"),
        PostalCode(code: "5176", city: "Loddefjord"),
        PostalCode(code: "5177", city: "Bjørøyhamn"),
        PostalCode(code: "5178", city: "Loddefjord"),
        PostalCode(code: "5179", city: "Godvik"),
        PostalCode(code: "5183", city: "Olsvik"),
        PostalCode(code: "5184", city: "Olsvik"),
        PostalCode(code: "5200", city: "Os"),
        PostalCode(code: "5201", city: "Os"),
        PostalCode(code: "5202", city: "Os"),
        PostalCode(code: "5203", city: "Os"),
        PostalCode(code: "5206", city: "Os"),
        PostalCode(code: "5207", city: "Søfteland"),
        PostalCode(code: "5208", city: "Os"),
        PostalCode(code: "5209", city: "Os"),
        PostalCode(code: "5210", city: "Os"),
        PostalCode(code: "5211", city: "Os"),
        PostalCode(code: "5212", city: "Søfteland"),
        PostalCode(code: "5213", city: "Lepsøy"),
        PostalCode(code: "5214", city: "Lysekloster"),
        PostalCode(code: "5215", city: "Lysekloster"),
        PostalCode(code: "5216", city: "Lepsøy"),
        PostalCode(code: "5217", city: "Hagavik"),
        PostalCode(code: "5218", city: "Nordstrøno"),
        PostalCode(code: "5221", city: "Nesttun"),
        PostalCode(code: "5222", city: "Nesttun"),
        PostalCode(code: "5223", city: "Nesttun"),
        PostalCode(code: "5224", city: "Nesttun"),
        PostalCode(code: "5225", city: "Nesttun"),
        PostalCode(code: "5226", city: "Nesttun"),
        PostalCode(code: "5227", city: "Nesttun"),
        PostalCode(code: "5228", city: "Nesttun"),
        PostalCode(code: "5229", city: "Kalandseidet"),
        PostalCode(code: "5230", city: "Paradis"),
        PostalCode(code: "5231", city: "Paradis"),
        PostalCode(code: "5232", city: "Paradis"),
        PostalCode(code: "5235", city: "Rådal"),
        PostalCode(code: "5236", city: "Rådal"),
        PostalCode(code: "5237", city: "Rådal"),
        PostalCode(code: "5238", city: "Rådal"),
        PostalCode(code: "5239", city: "Rådal"),
        PostalCode(code: "5243", city: "Fana"),
        PostalCode(code: "5244", city: "Fana"),
        PostalCode(code: "5251", city: "Søreidgrend"),
        PostalCode(code: "5252", city: "Søreidgrend"),
        PostalCode(code: "5253", city: "Sandsli"),
        PostalCode(code: "5254", city: "Sandsli"),
        PostalCode(code: "5257", city: "Kokstad"),
        PostalCode(code: "5258", city: "Blomsterdalen"),
        PostalCode(code: "5259", city: "Hjellestad"),
        PostalCode(code: "5260", city: "Indre Arna"),
        PostalCode(code: "5261", city: "Indre Arna"),
        PostalCode(code: "5262", city: "Arnatveit"),
        PostalCode(code: "5263", city: "Trengereid"),
        PostalCode(code: "5264", city: "Garnes"),
        PostalCode(code: "5265", city: "Ytre Arna"),
        PostalCode(code: "5267", city: "Espeland"),
        PostalCode(code: "5268", city: "Haukeland"),
        PostalCode(code: "5281", city: "Valestrandsfossen"),
        PostalCode(code: "5282", city: "Lonevåg"),
        PostalCode(code: "5283", city: "Fotlandsvåg"),
        PostalCode(code: "5284", city: "Tyssebotnen"),
        PostalCode(code: "5285", city: "Bruvik"),
        PostalCode(code: "5286", city: "Haus"),
        PostalCode(code: "5291", city: "Valestrandsfossen"),
        PostalCode(code: "5293", city: "Lonevåg"),
        PostalCode(code: "5299", city: "Haus"),
        PostalCode(code: "5300", city: "Kleppestø"),
        PostalCode(code: "5301", city: "Kleppestø"),
        PostalCode(code: "5302", city: "Strusshamn"),
        PostalCode(code: "5303", city: "Follese"),
        PostalCode(code: "5304", city: "Hetlevik"),
        PostalCode(code: "5305", city: "Florvåg"),
        PostalCode(code: "5306", city: "Erdal"),
        PostalCode(code: "5307", city: "Ask"),
        PostalCode(code: "5308", city: "Kleppestø"),
        PostalCode(code: "5309", city: "Kleppestø"),
        PostalCode(code: "5310", city: "Hauglandshella"),
        PostalCode(code: "5311", city: "Kjerrgarden"),
        PostalCode(code: "5314", city: "Kjerrgarden"),
        PostalCode(code: "5315", city: "Herdla"),
        PostalCode(code: "5318", city: "Strusshamn"),
        PostalCode(code: "5319", city: "Kleppestø"),
        PostalCode(code: "5321", city: "Kleppestø"),
        PostalCode(code: "5322", city: "Kleppestø"),
        PostalCode(code: "5323", city: "Kleppestø"),
        PostalCode(code: "5325", city: "Follese"),
        PostalCode(code: "5326", city: "Ask"),
        PostalCode(code: "5327", city: "Hauglandshella"),
        PostalCode(code: "5329", city: "Florvåg"),
        PostalCode(code: "5331", city: "Rong"),
        PostalCode(code: "5333", city: "Tjeldstø"),
        PostalCode(code: "5334", city: "Hellesøy"),
        PostalCode(code: "5335", city: "Hernar"),
        PostalCode(code: "5336", city: "Tjeldstø"),
        PostalCode(code: "5337", city: "Rong"),
        PostalCode(code: "5341", city: "Straume"),
        PostalCode(code: "5342", city: "Straume"),
        PostalCode(code: "5343", city: "Straume"),
        PostalCode(code: "5345", city: "Knarrevik"),
        PostalCode(code: "5346", city: "Ågotnes"),
        PostalCode(code: "5347", city: "Ågotnes"),
        PostalCode(code: "5350", city: "Brattholmen"),
        PostalCode(code: "5353", city: "Straume"),
        PostalCode(code: "5354", city: "Straume"),
        PostalCode(code: "5355", city: "Knarrevik"),
        PostalCode(code: "5357", city: "Fjell"),
        PostalCode(code: "5358", city: "Fjell"),
        PostalCode(code: "5360", city: "Kolltveit"),
        PostalCode(code: "5363", city: "Ågotnes"),
        PostalCode(code: "5365", city: "Turøy"),
        PostalCode(code: "5366", city: "Misje"),
        PostalCode(code: "5371", city: "Skogsvåg"),
        PostalCode(code: "5374", city: "Steinsland"),
        PostalCode(code: "5378", city: "Klokkarvik"),
        PostalCode(code: "5379", city: "Steinsland"),
        PostalCode(code: "5380", city: "Tælavåg"),
        PostalCode(code: "5381", city: "Glesvær"),
        PostalCode(code: "5382", city: "Skogsvåg"),
        PostalCode(code: "5384", city: "Torangsvåg"),
        PostalCode(code: "5385", city: "Bakkasund "),
        PostalCode(code: "5387", city: "Møkster"),
        PostalCode(code: "5388", city: "Litlakalsøy"),
        PostalCode(code: "5392", city: "Storebø"),
        PostalCode(code: "5393", city: "Storebø"),
        PostalCode(code: "5394", city: "Kolbeinsvik"),
        PostalCode(code: "5396", city: "Vestre Vinnesvåg"),
        PostalCode(code: "5397", city: "Bekkjarvik"),
        PostalCode(code: "5398", city: "Stolmen"),
        PostalCode(code: "5399", city: "Bekkjarvik"),
        PostalCode(code: "5401", city: "Stord"),
        PostalCode(code: "5402", city: "Stord"),
        PostalCode(code: "5403", city: "Stord"),
        PostalCode(code: "5404", city: "Stord"),
        PostalCode(code: "5406", city: "Stord"),
        PostalCode(code: "5407", city: "Stord"),
        PostalCode(code: "5408", city: "Sagvåg"),
        PostalCode(code: "5409", city: "Stord"),
        PostalCode(code: "5410", city: "Sagvåg"),
        PostalCode(code: "5411", city: "Stord"),
        PostalCode(code: "5412", city: "Stord"),
        PostalCode(code: "5413", city: "Huglo"),
        PostalCode(code: "5414", city: "Stord"),
        PostalCode(code: "5415", city: "Stord"),
        PostalCode(code: "5416", city: "Stord"),
        PostalCode(code: "5417", city: "Stord"),
        PostalCode(code: "5418", city: "Fitjar"),
        PostalCode(code: "5419", city: "Fitjar"),
        PostalCode(code: "5420", city: "Rubbestadneset"),
        PostalCode(code: "5423", city: "Brandasun"),
        PostalCode(code: "5427", city: "Urangsvåg"),
        PostalCode(code: "5428", city: "Foldrøyhamn"),
        PostalCode(code: "5430", city: "Bremnes"),
        PostalCode(code: "5437", city: "Finnås"),
        PostalCode(code: "5440", city: "Mosterhamn"),
        PostalCode(code: "5443", city: "Bømlo"),
        PostalCode(code: "5444", city: "Espevær"),
        PostalCode(code: "5445", city: "Bremnes"),
        PostalCode(code: "5447", city: "Mosterhamn"),
        PostalCode(code: "5449", city: "Bømlo"),
        PostalCode(code: "5450", city: "Sunde i Sunnhordland"),
        PostalCode(code: "5451", city: "Valen"),
        PostalCode(code: "5452", city: "Sandvoll"),
        PostalCode(code: "5453", city: "Utåker"),
        PostalCode(code: "5454", city: "Sæbøvik"),
        PostalCode(code: "5455", city: "Halsnøy Kloster"),
        PostalCode(code: "5457", city: "Høylandsbygd"),
        PostalCode(code: "5458", city: "Arnavik"),
        PostalCode(code: "5459", city: "Fjelberg"),
        PostalCode(code: "5460", city: "Husnes"),
        PostalCode(code: "5462", city: "Herøysundet"),
        PostalCode(code: "5463", city: "Uskedalen"),
        PostalCode(code: "5464", city: "Dimmelsvik"),
        PostalCode(code: "5465", city: "Uskedalen"),
        PostalCode(code: "5470", city: "Rosendal"),
        PostalCode(code: "5472", city: "Seimsfoss"),
        PostalCode(code: "5473", city: "Snilstveitøy"),
        PostalCode(code: "5474", city: "Løfallstrand"),
        PostalCode(code: "5475", city: "Ænes"),
        PostalCode(code: "5476", city: "Mauranger"),
        PostalCode(code: "5480", city: "Husnes"),
        PostalCode(code: "5484", city: "Sæbøvik"),
        PostalCode(code: "5486", city: "Rosendal"),
        PostalCode(code: "5498", city: "Matre"),
        PostalCode(code: "5499", city: "Åkra"),
        PostalCode(code: "5501", city: "Haugesund"),
        PostalCode(code: "5502", city: "Haugesund"),
        PostalCode(code: "5503", city: "Haugesund"),
        PostalCode(code: "5504", city: "Haugesund"),
        PostalCode(code: "5505", city: "Haugesund"),
        PostalCode(code: "5506", city: "Haugesund"),
        PostalCode(code: "5507", city: "Haugesund"),
        PostalCode(code: "5508", city: "Karmsund"),
        PostalCode(code: "5509", city: "Haugesund"),
        PostalCode(code: "5511", city: "Haugesund"),
        PostalCode(code: "5512", city: "Haugesund"),
        PostalCode(code: "5514", city: "Haugesund"),
        PostalCode(code: "5515", city: "Haugesund"),
        PostalCode(code: "5516", city: "Haugesund"),
        PostalCode(code: "5517", city: "Haugesund"),
        PostalCode(code: "5518", city: "Haugesund"),
        PostalCode(code: "5519", city: "Haugesund"),
        PostalCode(code: "5521", city: "Haugesund"),
        PostalCode(code: "5522", city: "Haugesund"),
        PostalCode(code: "5523", city: "Haugesund"),
        PostalCode(code: "5525", city: "Haugesund"),
        PostalCode(code: "5527", city: "Haugesund"),
        PostalCode(code: "5528", city: "Haugesund"),
        PostalCode(code: "5529", city: "Haugesund"),
        PostalCode(code: "5531", city: "Haugesund"),
        PostalCode(code: "5532", city: "Haugesund"),
        PostalCode(code: "5533", city: "Haugesund"),
        PostalCode(code: "5534", city: "Haugesund"),
        PostalCode(code: "5535", city: "Haugesund"),
        PostalCode(code: "5536", city: "Haugesund"),
        PostalCode(code: "5537", city: "Haugesund"),
        PostalCode(code: "5538", city: "Haugesund"),
        PostalCode(code: "5541", city: "Kolnes"),
        PostalCode(code: "5542", city: "Karmsund"),
        PostalCode(code: "5544", city: "Vormedal"),
        PostalCode(code: "5545", city: "Vormedal"),
        PostalCode(code: "5546", city: "Røyksund"),
        PostalCode(code: "5547", city: "Utsira"),
        PostalCode(code: "5548", city: "Feøy"),
        PostalCode(code: "5549", city: "Røvær"),
        PostalCode(code: "5550", city: "Sveio"),
        PostalCode(code: "5551", city: "Auklandshamn"),
        PostalCode(code: "5554", city: "Valevåg"),
        PostalCode(code: "5555", city: "Førde i Hordaland"),
        PostalCode(code: "5556", city: "Førde i Hordaland"),
        PostalCode(code: "5559", city: "Sveio"),
        PostalCode(code: "5560", city: "Nedstrand"),
        PostalCode(code: "5561", city: "Bokn"),
        PostalCode(code: "5562", city: "Nedstrand"),
        PostalCode(code: "5563", city: "Førresfjorden"),
        PostalCode(code: "5565", city: "Tysværvåg"),
        PostalCode(code: "5566", city: "Hervik"),
        PostalCode(code: "5567", city: "Skjoldastraumen"),
        PostalCode(code: "5568", city: "Vikebygd"),
        PostalCode(code: "5569", city: "Bokn"),
        PostalCode(code: "5570", city: "Aksdal"),
        PostalCode(code: "5574", city: "Skjold"),
        PostalCode(code: "5575", city: "Aksdal"),
        PostalCode(code: "5576", city: "Øvre Vats"),
        PostalCode(code: "5578", city: "Nedre Vats"),
        PostalCode(code: "5580", city: "Ølen"),
        PostalCode(code: "5582", city: "Ølensvåg"),
        PostalCode(code: "5583", city: "Vikedal"),
        PostalCode(code: "5584", city: "Bjoa"),
        PostalCode(code: "5585", city: "Sandeid"),
        PostalCode(code: "5586", city: "Vikedal"),
        PostalCode(code: "5588", city: "Ølen"),
        PostalCode(code: "5589", city: "Sandeid"),
        PostalCode(code: "5590", city: "Etne"),
        PostalCode(code: "5591", city: "Etne"),
        PostalCode(code: "5593", city: "Skånevik"),
        PostalCode(code: "5594", city: "Skånevik"),
        PostalCode(code: "5595", city: "Førresfjorden"),
        PostalCode(code: "5596", city: "Markhus"),
        PostalCode(code: "5598", city: "Fjæra"),
        PostalCode(code: "5600", city: "Norheimsund"),
        PostalCode(code: "5601", city: "Norheimsund"),
        PostalCode(code: "5602", city: "Norheimsund"),
        PostalCode(code: "5604", city: "Øystese"),
        PostalCode(code: "5605", city: "Ålvik"),
        PostalCode(code: "5610", city: "Øystese"),
        PostalCode(code: "5612", city: "Stein"),
        PostalCode(code: "5614", city: "Ålvik"),
        PostalCode(code: "5620", city: "Tørvikbygd"),
        PostalCode(code: "5626", city: "Kysnesstrand"),
        PostalCode(code: "5627", city: "Jondal"),
        PostalCode(code: "5628", city: "Herand"),
        PostalCode(code: "5629", city: "Jondal"),
        PostalCode(code: "5630", city: "Strandebarm"),
        PostalCode(code: "5631", city: "Strandebarm"),
        PostalCode(code: "5632", city: "Omastrand"),
        PostalCode(code: "5633", city: "Omastrand"),
        PostalCode(code: "5635", city: "Hatlestrand"),
        PostalCode(code: "5636", city: "Varaldsøy"),
        PostalCode(code: "5637", city: "Ølve"),
        PostalCode(code: "5640", city: "Eikelandsosen"),
        PostalCode(code: "5641", city: "Fusa"),
        PostalCode(code: "5642", city: "Holmefjord"),
        PostalCode(code: "5643", city: "Strandvik"),
        PostalCode(code: "5644", city: "Sævareid"),
        PostalCode(code: "5645", city: "Sævareid"),
        PostalCode(code: "5646", city: "Nordtveitgrend"),
        PostalCode(code: "5647", city: "Baldersheim"),
        PostalCode(code: "5648", city: "Fusa"),
        PostalCode(code: "5649", city: "Eikelandsosen"),
        PostalCode(code: "5650", city: "Tysse"),
        PostalCode(code: "5651", city: "Tysse"),
        PostalCode(code: "5652", city: "Årland"),
        PostalCode(code: "5653", city: "Årland"),
        PostalCode(code: "5680", city: "Tysnes"),
        PostalCode(code: "5683", city: "Reksteren"),
        PostalCode(code: "5685", city: "Uggdal"),
        PostalCode(code: "5687", city: "Flatråker"),
        PostalCode(code: "5690", city: "Lundegrend"),
        PostalCode(code: "5693", city: "Årbakka"),
        PostalCode(code: "5694", city: "Onarheim"),
        PostalCode(code: "5695", city: "Uggdal"),
        PostalCode(code: "5696", city: "Tysnes"),
        PostalCode(code: "5700", city: "Voss"),
        PostalCode(code: "5701", city: "Voss"),
        PostalCode(code: "5702", city: "Voss"),
        PostalCode(code: "5703", city: "Voss"),
        PostalCode(code: "5704", city: "Voss"),
        PostalCode(code: "5705", city: "Voss"),
        PostalCode(code: "5706", city: "Voss"),
        PostalCode(code: "5707", city: "Evanger"),
        PostalCode(code: "5708", city: "Voss"),
        PostalCode(code: "5709", city: "Voss"),
        PostalCode(code: "5710", city: "Skulestadmo"),
        PostalCode(code: "5711", city: "Skulestadmo"),
        PostalCode(code: "5712", city: "Vossestrand"),
        PostalCode(code: "5713", city: "Vossestrand"),
        PostalCode(code: "5714", city: "Voss"),
        PostalCode(code: "5715", city: "Stalheim"),
        PostalCode(code: "5718", city: "Myrda"),
        PostalCode(code: "5719", city: "Finse"),
        PostalCode(code: "5720", city: "Stanghelle"),
        PostalCode(code: "5721", city: "Dalekvam"),
        PostalCode(code: "5722", city: "Dalekvam"),
        PostalCode(code: "5723", city: "Bolstadøyri"),
        PostalCode(code: "5724", city: "Stanghelle"),
        PostalCode(code: "5725", city: "Vaksdal"),
        PostalCode(code: "5726", city: "Vaksdal"),
        PostalCode(code: "5727", city: "Stamnes"),
        PostalCode(code: "5728", city: "Eidslandet"),
        PostalCode(code: "5729", city: "Modalen"),
        PostalCode(code: "5730", city: "Ulvik"),
        PostalCode(code: "5731", city: "Ulvik"),
        PostalCode(code: "5732", city: "Modalen"),
        PostalCode(code: "5733", city: "Granvin"),
        PostalCode(code: "5734", city: "Vallavik"),
        PostalCode(code: "5736", city: "Granvin"),
        PostalCode(code: "5741", city: "Aurland"),
        PostalCode(code: "5742", city: "Flåm"),
        PostalCode(code: "5743", city: "Flåm"),
        PostalCode(code: "5745", city: "Aurland"),
        PostalCode(code: "5746", city: "Undredal"),
        PostalCode(code: "5747", city: "Gudvangen"),
        PostalCode(code: "5748", city: "Styvi"),
        PostalCode(code: "5750", city: "Odda"),
        PostalCode(code: "5751", city: "Odda"),
        PostalCode(code: "5752", city: "Odda"),
        PostalCode(code: "5760", city: "Røldal"),
        PostalCode(code: "5763", city: "Skare"),
        PostalCode(code: "5770", city: "Tyssedal"),
        PostalCode(code: "5773", city: "Hovland"),
        PostalCode(code: "5775", city: "Nå"),
        PostalCode(code: "5776", city: "Nå"),
        PostalCode(code: "5777", city: "Grimo"),
        PostalCode(code: "5778", city: "Utne"),
        PostalCode(code: "5779", city: "Utne"),
        PostalCode(code: "5780", city: "Kinsarvik"),
        PostalCode(code: "5781", city: "Lofthus"),
        PostalCode(code: "5782", city: "Kinsarvik"),
        PostalCode(code: "5783", city: "Eidfjord"),
        PostalCode(code: "5784", city: "Øvre Eidfjord"),
        PostalCode(code: "5785", city: "Vøringsfoss"),
        PostalCode(code: "5786", city: "Eidfjord"),
        PostalCode(code: "5787", city: "Lofthus"),
        PostalCode(code: "5788", city: "Kinsarvik"),
        PostalCode(code: "5802", city: "Bergen"),
        PostalCode(code: "5803", city: "Bergen"),
        PostalCode(code: "5804", city: "Bergen"),
        PostalCode(code: "5805", city: "Bergen"),
        PostalCode(code: "5806", city: "Bergen"),
        PostalCode(code: "5807", city: "Bergen"),
        PostalCode(code: "5808", city: "Bergen"),
        PostalCode(code: "5809", city: "Bergen"),
        PostalCode(code: "5810", city: "Bergen"),
        PostalCode(code: "5811", city: "Bergen"),
        PostalCode(code: "5812", city: "Bergen"),
        PostalCode(code: "5813", city: "Bergen"),
        PostalCode(code: "5814", city: "Bergen"),
        PostalCode(code: "5815", city: "Bergen"),
        PostalCode(code: "5816", city: "Bergen"),
        PostalCode(code: "5817", city: "Bergen"),
        PostalCode(code: "5818", city: "Bergen"),
        PostalCode(code: "5819", city: "Bergen"),
        PostalCode(code: "5820", city: "Bergen"),
        PostalCode(code: "5821", city: "Bergen"),
        PostalCode(code: "5822", city: "Bergen"),
        PostalCode(code: "5823", city: "Bergen"),
        PostalCode(code: "5824", city: "Bergen"),
        PostalCode(code: "5825", city: "Bergen"),
        PostalCode(code: "5826", city: "Bergen"),
        PostalCode(code: "5827", city: "Bergen"),
        PostalCode(code: "5828", city: "Bergen"),
        PostalCode(code: "5829", city: "Bergen"),
        PostalCode(code: "5830", city: "Bergen"),
        PostalCode(code: "5831", city: "Bergen"),
        PostalCode(code: "5832", city: "Bergen"),
        PostalCode(code: "5833", city: "Bergen"),
        PostalCode(code: "5834", city: "Bergen"),
        PostalCode(code: "5835", city: "Bergen"),
        PostalCode(code: "5836", city: "Bergen"),
        PostalCode(code: "5837", city: "Bergen"),
        PostalCode(code: "5838", city: "Bergen"),
        PostalCode(code: "5841", city: "Bergen"),
        PostalCode(code: "5843", city: "Bergen"),
        PostalCode(code: "5844", city: "Bergen"),
        PostalCode(code: "5845", city: "Bergen"),
        PostalCode(code: "5847", city: "Bergen"),
        PostalCode(code: "5848", city: "Bergen"),
        PostalCode(code: "5849", city: "Bergen"),
        PostalCode(code: "5851", city: "Bergen"),
        PostalCode(code: "5852", city: "Bergen"),
        PostalCode(code: "5853", city: "Bergen"),
        PostalCode(code: "5854", city: "Bergen"),
        PostalCode(code: "5855", city: "Bergen"),
        PostalCode(code: "5857", city: "Bergen"),
        PostalCode(code: "5858", city: "Bergen"),
        PostalCode(code: "5859", city: "Bergen"),
        PostalCode(code: "5861", city: "Bergen"),
        PostalCode(code: "5862", city: "Bergen"),
        PostalCode(code: "5863", city: "Bergen"),
        PostalCode(code: "5864", city: "Bergen"),
        PostalCode(code: "5865", city: "Bergen"),
        PostalCode(code: "5866", city: "Bergen"),
        PostalCode(code: "5867", city: "Bergen"),
        PostalCode(code: "5868", city: "Bergen"),
        PostalCode(code: "5869", city: "Bergen"),
        PostalCode(code: "5872", city: "Bergen"),
        PostalCode(code: "5873", city: "Bergen"),
        PostalCode(code: "5876", city: "Bergen"),
        PostalCode(code: "5877", city: "Bergen"),
        PostalCode(code: "5878", city: "Bergen"),
        PostalCode(code: "5879", city: "Bergen"),
        PostalCode(code: "5881", city: "Bergen"),
        PostalCode(code: "5884", city: "Bergen"),
        PostalCode(code: "5886", city: "Bergen"),
        PostalCode(code: "5887", city: "Bergen"),
        PostalCode(code: "5888", city: "Bergen"),
        PostalCode(code: "5889", city: "Bergen"),
        PostalCode(code: "5892", city: "Bergen"),
        PostalCode(code: "5893", city: "Bergen"),
        PostalCode(code: "5895", city: "Bergen"),
        PostalCode(code: "5896", city: "Bergen"),
        PostalCode(code: "5899", city: "Bergen"),
        PostalCode(code: "5902", city: "Isdalstø"),
        PostalCode(code: "5903", city: "Isdalstø"),
        PostalCode(code: "5904", city: "Isdalstø"),
        PostalCode(code: "5906", city: "Frekhaug"),
        PostalCode(code: "5907", city: "Alversund"),
        PostalCode(code: "5908", city: "Isdalstø"),
        PostalCode(code: "5911", city: "Alversund"),
        PostalCode(code: "5912", city: "Seim"),
        PostalCode(code: "5913", city: "Eikangervåg"),
        PostalCode(code: "5914", city: "Isdalstø"),
        PostalCode(code: "5915", city: "Hjelmås"),
        PostalCode(code: "5916", city: "Isdalstø"),
        PostalCode(code: "5917", city: "Rossland"),
        PostalCode(code: "5918", city: "Frekhaug"),
        PostalCode(code: "5919", city: "Frekhaug"),
        PostalCode(code: "5931", city: "Manger"),
        PostalCode(code: "5935", city: "Bøvågen"),
        PostalCode(code: "5936", city: "Manger"),
        PostalCode(code: "5937", city: "Bøvågen"),
        PostalCode(code: "5938", city: "Sæbøvågen"),
        PostalCode(code: "5939", city: "Sletta"),
        PostalCode(code: "5941", city: "Austrheim"),
        PostalCode(code: "5943", city: "Austrheim"),
        PostalCode(code: "5947", city: "Fedje"),
        PostalCode(code: "5948", city: "Fedje"),
        PostalCode(code: "5951", city: "Lindås"),
        PostalCode(code: "5952", city: "Fonnes"),
        PostalCode(code: "5953", city: "Fonnes"),
        PostalCode(code: "5954", city: "Mongstad "),
        PostalCode(code: "5955", city: "Lindås"),
        PostalCode(code: "5956", city: "Hundvin"),
        PostalCode(code: "5957", city: "Myking"),
        PostalCode(code: "5960", city: "Dalsøyra"),
        PostalCode(code: "5961", city: "Brekke"),
        PostalCode(code: "5962", city: "Bjordal"),
        PostalCode(code: "5963", city: "Dalsøyra"),
        PostalCode(code: "5964", city: "Brekke"),
        PostalCode(code: "5965", city: "Bjordal"),
        PostalCode(code: "5966", city: "Eivindvik"),
        PostalCode(code: "5967", city: "Eivindvik"),
        PostalCode(code: "5970", city: "Byrknesøy"),
        PostalCode(code: "5977", city: "Ånneland"),
        PostalCode(code: "5978", city: "Mjømna"),
        PostalCode(code: "5979", city: "Byrknesøy"),
        PostalCode(code: "5981", city: "Masfjordnes"),
        PostalCode(code: "5982", city: "Masfjordnes"),
        PostalCode(code: "5983", city: "Haugsvær"),
        PostalCode(code: "5984", city: "Matredal"),
        PostalCode(code: "5985", city: "Haugsvær"),
        PostalCode(code: "5986", city: "Hosteland"),
        PostalCode(code: "5987", city: "Hosteland"),
        PostalCode(code: "5991", city: "Ostereidet"),
        PostalCode(code: "5993", city: "Ostereidet"),
        PostalCode(code: "5994", city: "Vikanes")
                    
    ]

    @IBOutlet var searchPostelCode: UISearchBar!
    @IBOutlet var tableView: UITableView!

    var searchedPostalCodes = [PostalCode]()
    var searching = false
    var checked = [Bool]()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Set all checkmarks to false
        checked = Array(repeating: false, count: postalCodes.count)
        searchPostelCode.delegate = self
        
        oldCity = city
        oldPostalCode = postalCode
        
    }

    override func viewDidAppear(_ animated: Bool) {
        checked = Array(repeating: false, count: postalCodes.count)
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if searching {
            return searchedPostalCodes.count
        } else {
            return postalCodes.count
        }
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell")

        // Configure the cell
        if searching {
            cell?.textLabel?.text = searchedPostalCodes[indexPath.row].code
            cell?.detailTextLabel?.text = searchedPostalCodes[indexPath.row].city
        } else {
            cell?.textLabel?.text = postalCodes[indexPath.row].code
            cell?.detailTextLabel?.text = postalCodes[indexPath.row].city
        }

        return cell!
    }

    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        searchedPostalCodes = postalCodes.filter({ $0.city.prefix(searchText.count) == searchText })
        searching = true
        tableView.reloadData()
    }
   
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)

        // Delete all checkmarks
        checked = Array(repeating: false, count: postalCodes.count)
        
        let rowCount = tableView.numberOfRows(inSection: 0)
        for index in 0 ... rowCount {
            if let cell = tableView.cellForRow(at: NSIndexPath(row: index, section: 0) as IndexPath) {
                if cell.accessoryType == .checkmark {
                    cell.accessoryType = .none
                }
            }
        }
        
        // Resetter postalCode and city
        postalCode = ""
        city = ""
        
        // Set a checkmark at cellForRow and
        // Store the selected city and postalCode
        if let cell = tableView.cellForRow(at: indexPath as IndexPath) {
            cell.accessoryType = .checkmark
            city = String(cell.detailTextLabel!.text!)
            postalCode = String(cell.textLabel!.text!)
        }
    }

    // Close the onboard keyboard
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        searchPostelCode.endEditing(true)
        searchPostelCode.text = ""
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        print("Antall tegn i city = " + (String(city.count) + " " + postalCode + " " + city) as Any)
        
        if city.count == 0 {
           city = oldCity
        }
        
        if postalCode.count == 0 {
           postalCode = oldPostalCode
        }
        
    }
    
}
